# Generated by Django 5.0.1 on 2024-01-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vip_status',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold')], max_length=50),
        ),
    ]
