# Generated by Django 5.0.1 on 2024-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_remove_userinfo_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="orders",
            field=models.BigIntegerField(),
        ),
    ]
