# Generated by Django 5.0.1 on 2024-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_loghistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="authenticationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("adminPassword", models.CharField(max_length=255)),
            ],
        ),
    ]
