# Generated by Django 5.0.1 on 2024-05-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_customer_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                default="default_profile_image.jpg", upload_to="profile_images/"
            ),
        ),
    ]
